name: tevalearn_miniapp
description: TevaLearn LMS MiniApp.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  soar_quest: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
